#!/usr/bin/env python3
from pathlib import Path
p=Path('build/LiveExec32/GuestFrameworks/AudioToolbox/AudioToolbox.m');s=p.read_text()
if 'LC32GuestAUGraphMagic' not in s:
 s+=r'''
#pragma mark Guest-owned AUGraph compatibility
#define LC32GuestAUGraphMagic 0x4c434147u
#define LC32GuestAUGraphMaximumNodes 64u
typedef struct {AUNode id;AudioComponentDescription desc;AudioUnit unit;AURenderCallbackStruct callback;BOOL hasCallback;} LC32GuestAUGraphNode;
typedef struct {uint32_t magic;pthread_mutex_t mutex;BOOL opened,initialized,running;AUNode next;uint32_t count;LC32GuestAUGraphNode nodes[LC32GuestAUGraphMaximumNodes];} LC32GuestAUGraph;
static LC32GuestAUGraph *LC32Graph(AUGraph v){LC32GuestAUGraph *g=(LC32GuestAUGraph *)v;return g&&g->magic==LC32GuestAUGraphMagic?g:NULL;}
static LC32GuestAUGraphNode *LC32GraphFind(LC32GuestAUGraph *g,AUNode id){for(uint32_t i=0;i<g->count;i++)if(g->nodes[i].id==id)return &g->nodes[i];return NULL;}
static OSStatus LC32GraphUnit(LC32GuestAUGraphNode *n){return n->unit?noErr:AudioComponentInstanceNew((AudioComponent)&LC32SilentRemoteIOComponent,(AudioComponentInstance *)&n->unit);}
OSStatus NewAUGraph(AUGraph *out){if(!out)return kAudio_ParamError;*out=NULL;LC32GuestAUGraph *g=calloc(1,sizeof(*g));if(!g)return kAudio_MemFullError;if(pthread_mutex_init(&g->mutex,NULL)){free(g);return kAudio_MemFullError;}g->magic=LC32GuestAUGraphMagic;g->next=1;*out=(AUGraph)g;return noErr;}
OSStatus DisposeAUGraph(AUGraph value){LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;AUGraphStop(value);pthread_mutex_lock(&g->mutex);for(uint32_t i=0;i<g->count;i++)if(g->nodes[i].unit)AudioComponentInstanceDispose((AudioComponentInstance)g->nodes[i].unit);g->magic=0;pthread_mutex_unlock(&g->mutex);pthread_mutex_destroy(&g->mutex);free(g);return noErr;}
OSStatus AUGraphAddNode(AUGraph value,const AudioComponentDescription *desc,AUNode *out){LC32GuestAUGraph *g=LC32Graph(value);if(!g||!desc||!out)return kAudio_ParamError;pthread_mutex_lock(&g->mutex);if(g->count==LC32GuestAUGraphMaximumNodes){pthread_mutex_unlock(&g->mutex);return kAudio_MemFullError;}LC32GuestAUGraphNode *n=&g->nodes[g->count++];n->id=g->next++;n->desc=*desc;*out=n->id;pthread_mutex_unlock(&g->mutex);return noErr;}
OSStatus AUGraphOpen(AUGraph value){LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;pthread_mutex_lock(&g->mutex);OSStatus status=noErr;for(uint32_t i=0;i<g->count&&status==noErr;i++)status=LC32GraphUnit(&g->nodes[i]);if(status==noErr)g->opened=YES;pthread_mutex_unlock(&g->mutex);return status;}
OSStatus AUGraphClose(AUGraph value){LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;AUGraphStop(value);pthread_mutex_lock(&g->mutex);for(uint32_t i=0;i<g->count;i++){if(g->nodes[i].unit)AudioComponentInstanceDispose((AudioComponentInstance)g->nodes[i].unit);g->nodes[i].unit=NULL;}g->opened=g->initialized=NO;pthread_mutex_unlock(&g->mutex);return noErr;}
OSStatus AUGraphNodeInfo(AUGraph value,AUNode id,AudioComponentDescription *desc,AudioUnit *unit){LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;pthread_mutex_lock(&g->mutex);LC32GuestAUGraphNode *n=LC32GraphFind(g,id);OSStatus status=n?LC32GraphUnit(n):kAUGraphErr_NodeNotFound;if(status==noErr){if(desc)*desc=n->desc;if(unit)*unit=n->unit;}pthread_mutex_unlock(&g->mutex);return status;}
OSStatus AUGraphConnectNodeInput(AUGraph value,AUNode source,UInt32 sourceOutput,AUNode destination,UInt32 destinationInput){(void)sourceOutput;(void)destinationInput;LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;pthread_mutex_lock(&g->mutex);BOOL found=LC32GraphFind(g,source)&&LC32GraphFind(g,destination);pthread_mutex_unlock(&g->mutex);return found?noErr:kAUGraphErr_NodeNotFound;}
OSStatus AUGraphSetNodeInputCallback(AUGraph value,AUNode id,UInt32 input,const AURenderCallbackStruct *callback){(void)input;LC32GuestAUGraph *g=LC32Graph(value);if(!g||!callback||!callback->inputProc)return kAudio_ParamError;pthread_mutex_lock(&g->mutex);LC32GuestAUGraphNode *n=LC32GraphFind(g,id);if(n){n->callback=*callback;n->hasCallback=YES;}pthread_mutex_unlock(&g->mutex);return n?noErr:kAUGraphErr_NodeNotFound;}
OSStatus AUGraphInitialize(AUGraph value){LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;OSStatus status=AUGraphOpen(value);if(status)return status;pthread_mutex_lock(&g->mutex);g->initialized=YES;pthread_mutex_unlock(&g->mutex);return noErr;}
OSStatus AUGraphUninitialize(AUGraph value){LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;AUGraphStop(value);pthread_mutex_lock(&g->mutex);g->initialized=NO;pthread_mutex_unlock(&g->mutex);return noErr;}
OSStatus AUGraphIsInitialized(AUGraph value,Boolean *out){LC32GuestAUGraph *g=LC32Graph(value);if(!g||!out)return kAudio_ParamError;pthread_mutex_lock(&g->mutex);*out=g->initialized;pthread_mutex_unlock(&g->mutex);return noErr;}
OSStatus AUGraphIsRunning(AUGraph value,Boolean *out){LC32GuestAUGraph *g=LC32Graph(value);if(!g||!out)return kAudio_ParamError;pthread_mutex_lock(&g->mutex);*out=g->running;pthread_mutex_unlock(&g->mutex);return noErr;}
OSStatus AUGraphStart(AUGraph value){LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;OSStatus status=AUGraphInitialize(value);if(status)return status;pthread_mutex_lock(&g->mutex);LC32GuestAUGraphNode *output=NULL,*source=NULL;for(uint32_t i=0;i<g->count;i++){if(!source&&g->nodes[i].hasCallback)source=&g->nodes[i];if(!output&&g->nodes[i].desc.componentType==kAudioUnitType_Output)output=&g->nodes[i];}if(!output&&g->count)output=&g->nodes[0];if(!output){pthread_mutex_unlock(&g->mutex);return kAUGraphErr_NodeNotFound;}status=LC32GraphUnit(output);if(status==noErr&&source)status=AudioUnitSetProperty(output->unit,kAudioUnitProperty_SetRenderCallback,kAudioUnitScope_Global,0,&source->callback,sizeof(source->callback));if(status==noErr)status=AudioUnitInitialize(output->unit);if(status==noErr)status=AudioOutputUnitStart(output->unit);if(status==noErr)g->running=YES;pthread_mutex_unlock(&g->mutex);return status;}
OSStatus AUGraphStop(AUGraph value){LC32GuestAUGraph *g=LC32Graph(value);if(!g)return kAudio_ParamError;pthread_mutex_lock(&g->mutex);OSStatus status=noErr;for(uint32_t i=0;i<g->count;i++)if(g->nodes[i].unit){OSStatus current=AudioOutputUnitStop(g->nodes[i].unit);if(status==noErr&&current!=noErr)status=current;}g->running=NO;pthread_mutex_unlock(&g->mutex);return status;}
'''
 p.write_text(s)
print('AudioToolbox: added guest-owned AUGraph over safe RemoteIO PCM output')
